name: whatsapp_temp_builder
description: WhatsApp Template Manager
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  mime: ^1.0.4                 # added for MIME type detection

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env